### ISSUE TITLE
We need handle this error code. 

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#608]
```
Unknown Message (code 10008)- See Discord's JSON Error Codes
```

**Comment by LucasMull** [comment]
Did you get this under specific circumnstances?

**Comment by LucasMull** [comment]
It seems to trigger at a invalid message_id endpoint, does this error crash the bot?

**Comment by LucasMull** [comment]
This error occurred because a invalid message id was sent, probably sent a 0 id accidentally. To avoid this error you need to check every message id beforehand, and make sure they are different than 0 (or not memory trash). I believe this is not a issue, but the check should be done inside of the function that does the endpoints calling @mlite.

**Comment by mlite** [comment]
Got it. Please close it.
