### ISSUE TITLE
Delete `install` target from Makefile

### ISSUE THREAD

**Issue by mlite** [cee-studio/orca#681]
We should not support install at all.   It will create more problems as the code is constantly changed, and there is no app level dependency for C.

**Comment by LucasMull** [comment]
Why is that? If I want to include orca in one of my projects, I don't want that project to have a "needs to be compiled inside orca/bots" as a dependency.

**Comment by LucasMull** [comment]
1. We could start versioning orca, its not that hard. We just set a `VERSION` file in the top folder and have our Makefile use it as a environment variable. We can have the user check his version so that we know if its stale.
2. Delete install as you proposed but create single-file sources for each of the APIs.
3. Both?

**Comment by mlite** [comment]
> I see your point, but if I want to include orca in one of my projects, I don't want that project to have a "needs to be compiled inside orca/bots" as a dependency.

Do we know a real use case like this?

**Comment by mlite** [comment]
we can expand `add-ons` to support developing more sophisticated custom bots.

**Comment by LucasMull** [comment]
> > I see your point, but if I want to include orca in one of my projects, I don't want that project to have a "needs to be compiled inside orca/bots" as a dependency.
> 
> Do we know a real use case like this?

Here is a implementation using Orca from one of our members https://github.com/programmers-den/PDBot

**Comment by LucasMull** [comment]
All I'm saying is that I wouldn't use a library that makes it mandatory to build my project inside one of its folders. It would be pretty weird if in order to use sqlite/libcurl theres a pre-requisite of having to move my entire project inside a special folder used by them. I'd like to keep my project independent as its own thing without the side-effect of it becoming a fork to another library.

But thats only my personal take on it, which is why I think versioning might be a good middle-ground

**Comment by LucasMull** [comment]
I have added a special my_bot at a64d6e3ea4fc652e558ed850cc1b57f4ac7c4b9c folder for this purposes, and a getting started [guide](https://github.com/cee-studio/orca#getting-started). Since we have settled on keeping the `install` rule for more advanced users, I think we can now close this.
